name: Push on main branch

on:
  push:
    branches:
      - main

jobs:
  auto-tag-and-publish:
    name: Auto-tag and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      image-tag: ${{ steps.tagger.outputs.new_tag }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run auto tag script
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          
          ./scripts/auto_tag.sh
      
      - name: Get the new tag without 'v' prefix
        id: tagger
        run: |
          NEW_TAG=$(git describe --tags --abbrev=0)
          NEW_TAG_WITHOUT_V=${NEW_TAG#v}
          echo "new_tag=$NEW_TAG_WITHOUT_V" >> $GITHUB_OUTPUT
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tagger.outputs.new_tag }}
            ghcr.io/${{ github.repository }}:latest-rc
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    needs: auto-tag-and-publish
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      GKE_CLUSTER_NAME: uat
      GKE_CLUSTER_ZONE: europe-central2
      GKE_BASTION_NAME: gke-uat-bastion
      GKE_BASTION_ZONE: europe-central2-a
      HELM_NAMESPACE: clearnet-uat
      HELM_RELEASE: clearnode
      HELM_CONFIG_ENV: uat
      KUBECONFIG: kubeconfig.conf

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GKE_UAT_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        install_components: gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: |-
        gcloud container clusters get-credentials ${GKE_CLUSTER_NAME} \
          --project ${PROJECT_ID} \
          --zone ${GKE_CLUSTER_ZONE} \
          --internal-ip

    - name: Port-forward to GKE Bastion
      run: |-
        gcloud compute ssh ${GKE_BASTION_NAME} \
          --tunnel-through-iap \
          --project ${PROJECT_ID} \
          --zone ${GKE_BASTION_ZONE} \
          -- -NL8888:127.0.0.1:8888 &
        sleep 5

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Release
      env:
        HTTPS_PROXY: http://localhost:8888
      run: |-
        helm upgrade -i ${HELM_RELEASE} chart \
          -n ${HELM_NAMESPACE} \
          --reuse-values \
          -f chart/config/${HELM_CONFIG_ENV}/clearnode.yaml \
          --set image.tag="${{ needs.auto-tag-and-publish.outputs.image-tag }}"
