config:
  args: ["clearnode"]
  logLevel: debug
  database:
    driver: postgres
    host: postgresql.core
    port: 5432
    name: clearnet_uat
    user: clearnet_uat_admin
  envSecret: ""
  extraEnvs:
    POLYGON_CUSTODY_CONTRACT_ADDRESS: "0x461B74f2fB8DaB2Dda51ed3E82ad43Ba67153E54"
    ETH_SEPOLIA_CUSTODY_CONTRACT_ADDRESS: "0xa3f2f64455c9f8D68d9dCAeC2605D64680FaF898"

image:
  repository: ghcr.io/erc7824/clearnode
  tag: 0.0.1-rc.12

service:
  http:
    enabled: true
    port: 8000
    path: /

metrics:
  enabled: true
  podmonitoring:
    enabled: true
  port: 4242
  endpoint: "/metrics"

resources:
  limits:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 100Mi
  requests:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 100Mi

autoscaling:
  enabled: false

networking:
  externalHostname: canarynet.yellow.com
  tlsClusterIssuer: zerossl-prod
  gateway:
    enabled: false
  ingress:
    enabled: true
    className: nginx
    tls:
      enabled: true

imagePullSecret: ghcr-pull
